name: Update latest.json on gh-pages after release

on:
  release:
    types: [published]

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release metadata
        uses: actions/github-script@v6
        id: get-latest-json
        with:
          script: |
            const release = context.payload.release;
            const asset = release.assets.find(a => a.name === "latest.json");
            if (!asset) {
              throw new Error("latest.json not found in release assets.");
            }
            return asset.browser_download_url;
          result-encoding: string

      - name: Download latest.json
        run: curl -L ${{ steps.get-latest-json.outputs.result }} -o latest.json

      - name: Clone gh-pages branch
        run: |
          git clone --single-branch --branch gh-pages https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} gh-pages

      - name: Update latest.json
        run: |
          cp latest.json gh-pages/latest.json
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.json
          git commit -m "Update latest.json from release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin gh-pages
